'use strict';
const $=id=>document.getElementById(id),ids=['minutes','rate','service','servers','seed','arrivals','services'];
const defaults={minutes:30,rate:3,service:50,servers:3,seed:2026,arrivals:'random',services:'random'};
let result=null;
const text=(tag,value)=>{const e=document.createElement(tag);e.textContent=value;return e;};
function invalidate(){result=null;for(const id of ['csv','json','png'])$(id).disabled=true;$('status').textContent='设置已改变，请重新比较；下方保留的是上一次结果，不代表新设置。';}
function card(name,m){const e=document.createElement('article');e.className='card';e.append(text('h3',name));const b=text('p',m.meanWait.toFixed(1));b.className='big';b.append(text('small',' 秒平均等待'));e.append(b);const dl=document.createElement('dl');for(const [k,v] of [['P95等待',m.p95Wait.toFixed(1)+' 秒'],['最长等待',m.maxWait.toFixed(1)+' 秒'],['队列峰值',m.maxQueue+' 人'],['营业时段忙碌率',(m.utilization*100).toFixed(1)+'%'],['关门时已完成',m.completedByClose+' / '+m.count],['全部清空时刻',(m.clearAt/60).toFixed(1)+' 分钟']])dl.append(text('dt',k),text('dd',v));e.append(dl);return e;}
function draw(r){const c=$('chart'),g=c.getContext('2d'),w=c.width,h=c.height,left=65,right=25,top=35,bottom=55,maxT=Math.max(r.pooled.metrics.clearAt,r.separate.metrics.clearAt),maxQ=Math.max(1,r.pooled.metrics.maxQueue,r.separate.metrics.maxQueue);g.fillStyle='#faf8f1';g.fillRect(0,0,w,h);g.font='16px system-ui';g.lineWidth=1;g.setLineDash([]);const x=t=>left+t/maxT*(w-left-right),y=n=>h-bottom-n/maxQ*(h-top-bottom);for(let i=0;i<=4;i++){const n=maxQ*i/4;g.strokeStyle='#d6ddcf';g.beginPath();g.moveTo(left,y(n));g.lineTo(w-right,y(n));g.stroke();g.fillStyle='#203c35';g.fillText(n.toFixed(n%1?1:0),10,y(n)+5);}for(let i=0;i<=5;i++){const t=maxT*i/5;g.fillText((t/60).toFixed(1),x(t)-12,h-25);}g.fillText('分钟',w-48,h-6);g.strokeStyle='#879f8e';g.setLineDash([3,5]);g.beginPath();g.moveTo(x(r.horizon),top);g.lineTo(x(r.horizon),h-bottom);g.stroke();for(const [p,color,dash] of [['pooled','#26765f',[]],['separate','#bd4a29',[10,6]]]){g.strokeStyle=color;g.lineWidth=3;g.setLineDash(dash);g.beginPath();let previous=0;g.moveTo(x(0),y(0));for(const [t,n] of r[p].curve){g.lineTo(x(t),y(previous));g.lineTo(x(t),y(n));previous=n;}g.stroke();}g.setLineDash([]);}
function compute(){try{const c=Object.fromEntries(ids.map(id=>[id,['arrivals','services'].includes(id)?$(id).value:Number($(id).value)]));const r=QueueLab.run(c);result=r;$('cards').replaceChildren(card('01 / 共用一条队',r.pooled.metrics),card('02 / 各窗口独立排队',r.separate.metrics));draw(r);const load=c.rate*c.service/(60*c.servers);$('status').textContent=`本轮 ${r.jobs.length} 位虚构顾客，种子 ${c.seed}。名义负载 ${(load*100).toFixed(0)}%。`+(load>=1?' 设定的平均需求不低于服务能力，持续运行可能积压；本图仍模拟到全部清空。':' 单次随机结果仅供理解机制，不是现实预测。');for(const id of ['csv','json','png'])$(id).disabled=false;}catch(e){invalidate();$('status').textContent='无法计算：'+e.message;}}
function annotateChart(r){const g=$('chart').getContext('2d');g.font='14px system-ui';g.fillStyle='#26765f';g.fillText('实线：共用队列',65,20);g.fillStyle='#bd4a29';g.fillText('虚线：独立队列',245,20);g.fillStyle='#203c35';g.fillText('虚构模拟 · 等待人数 · 种子 '+r.config.seed+' · 非门店预测',435,20);}
const drawBase=draw;draw=function(r){drawBase(r);annotateChart(r);};
function save(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
ids.forEach(id=>$(id).addEventListener('input',invalidate));$('settings').onsubmit=e=>{e.preventDefault();compute();};
$('reset').onclick=()=>{if(!confirm('恢复示例参数并重新计算？'))return;for(const id of ids)$(id).value=defaults[id];compute();};
$('csv').onclick=()=>{if(result)save(new Blob(['\ufeff'+QueueLab.csv(result)],{type:'text/csv;charset=utf-8'}),'queue-experiment.csv');};
$('json').onclick=()=>{if(result)save(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}),'queue-experiment.json');};
$('png').onclick=()=>{if(result)$('chart').toBlob(b=>{if(b)save(b,'queue-experiment.png');},'image/png');};compute();
