const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Q=require('./engine.js');
const checks=[],base={minutes:30,rate:3,service:50,servers:3,seed:2026,arrivals:'random',services:'random'};
const jobs=[{id:1,arrival:0,service:100},{id:2,arrival:1,service:10},{id:3,arrival:2,service:10},{id:4,arrival:3,service:1}];
const p=Q.simulate(jobs,2,'pooled',1000),s=Q.simulate(jobs,2,'separate',1000);
assert.deepEqual(p.records.map(r=>r.wait),[0,0,9,18]);assert.deepEqual(s.records.map(r=>r.wait),[0,0,98,8]);assert.equal(p.metrics.meanWait,6.75);assert.equal(p.metrics.p95Wait,18);assert.equal(p.metrics.maxQueue,2);assert.equal(s.metrics.maxQueue,2);assert.equal(p.metrics.utilization,121/2000);checks.push('Hand-calculated paired-policy waits, nearest-rank P95, queue peak, busy time');
const close=Q.simulate([{id:1,arrival:9,service:20},{id:2,arrival:9.5,service:5}],1,'pooled',10);assert.equal(close.metrics.utilization,.1);assert.equal(close.metrics.completedByClose,0);assert.equal(close.metrics.clearAt,34);assert.equal(close.records[1].wait,19.5);assert.equal(Q.simulate([],2,'pooled',10).metrics.meanWait,0);checks.push('Closing clips utilization but retains all waits and drains jobs; zero arrivals');
const equal=Q.simulate([{id:1,arrival:0,service:10},{id:2,arrival:10,service:10}],1,'separate',30);assert.equal(equal.metrics.maxQueue,0);assert.equal(equal.metrics.meanWait,0);checks.push('Completion at arrival time is available immediately');
assert.deepEqual(Q.run(base),Q.run(base));assert.notDeepEqual(Q.generate(base),Q.generate({...base,seed:2027}));assert.deepEqual(Q.generate({...base,rate:0}),[]);assert.ok(Q.generate({...base,arrivals:'regular',services:'fixed'}).every(j=>j.service===50));checks.push('Seed repeatability, distinct seeds, zero rate, fixed duration');
for(const patch of [{seed:1.1},{seed:-1},{rate:NaN},{rate:21},{minutes:121},{service:0},{servers:0},{servers:1.5},{arrivals:'<script>'},{services:'bad'}])assert.throws(()=>Q.run({...base,...patch}));assert.throws(()=>Q.simulate([{arrival:2,service:1},{arrival:1,service:1}],1,'pooled',10));assert.throws(()=>Q.simulate([{arrival:10,service:1}],1,'pooled',10));checks.push('Bounds, malformed distributions and invalid chronology rejected');
// Separate event-driven oracle. It does not use production free-time assignment.
function oracle(input,c,policy){let i=0,time=0;const active=Array(c).fill(null),queues=Array.from({length:policy==='pooled'?1:c},()=>[]),out=[];const start=(j,k)=>{const r={...j,start:time,end:time+j.service,wait:time-j.arrival};active[k]=r;out.push(r);};
  while(i<input.length||active.some(Boolean)||queues.some(q=>q.length)){
    time=Math.min(i<input.length?input[i].arrival:Infinity,...active.map(r=>r?r.end:Infinity));
    for(let k=0;k<c;k++)if(active[k]&&active[k].end===time){active[k]=null;const queue=queues[policy==='pooled'?0:k];if(queue.length)start(queue.shift(),k);}
    while(i<input.length&&input[i].arrival===time){const j=input[i++];if(policy==='pooled'){const k=active.findIndex(r=>!r);if(k>=0)start(j,k);else queues[0].push(j);}else{let k=0;for(let x=1;x<c;x++)if(queues[x].length+!!active[x]<queues[k].length+!!active[k])k=x;if(active[k])queues[k].push(j);else start(j,k);}}
  }return out.sort((a,b)=>a.id-b.id);
}
for(let seed=0;seed<64;seed++){const c={...base,minutes:5,seed,rate:1+seed%20,servers:1+seed%8,services:seed%2?'fixed':'random'},r=Q.run(c);for(const policy of ['pooled','separate']){const expected=oracle(r.jobs,c.servers,policy);assert.deepEqual(r[policy].records.map(j=>[j.start,j.end,j.wait]),expected.map(j=>[j.start,j.end,j.wait]));const m=r[policy].metrics;assert.ok(m.utilization>=0&&m.utilization<=1+1e-12);assert.ok(r[policy].curve.every(v=>v[1]>=0));}}
checks.push('128 policy runs compared against an independent event-driven scheduling oracle');
const peak=Q.run({...base,minutes:120,rate:20,service:300,servers:1});assert.ok(peak.jobs.length<10000);assert.ok(peak.pooled.metrics.clearAt>peak.horizon);const one=Q.run({...base,servers:1});assert.deepEqual(one.pooled.records,one.separate.records);const csv=Q.csv(one);assert.equal(csv.split('\r\n').length,one.jobs.length*2+1);assert.ok(!/[=+@]/.test(csv));checks.push('Bounded high-load run, one-window equivalence and numeric-only CSV');
const out=path.join(__dirname,'test-output');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'engine-results.json'),JSON.stringify({timestamp:new Date().toISOString(),checks,status:'PASS'},null,2));console.log(checks);
