const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const out=path.join(__dirname,'test-output');fs.mkdirSync(out,{recursive:true});const b=await chromium.launch(),ctx=await b.newContext({acceptDownloads:true,viewport:{width:1440,height:1100}});await ctx.setOffline(true);const p=await ctx.newPage(),errors=[],requests=[],checks=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});p.on('dialog',d=>d.accept());await p.goto(pathToFileURL(path.join(__dirname,'index.html')).href);assert.equal(await p.locator('.card').count(),2);assert.match(await p.locator('#status').textContent(),/虚构顾客/);checks.push('Initial comparison rendered offline');
await p.locator('#rate').fill('0');assert.equal(await p.locator('#csv').isDisabled(),true);assert.match(await p.locator('#status').textContent(),/上一次/);await p.click('button[type=submit]');assert.match(await p.locator('#status').textContent(),/0 位/);assert.deepEqual(await p.locator('.big').allTextContents(),['0.0 秒平均等待','0.0 秒平均等待']);checks.push('Stale export disabled; zero arrivals render safe empty metrics');
await p.locator('#servers').fill('0');await p.click('button[type=submit]');assert.equal(await p.locator('#csv').isDisabled(),true);await p.click('#reset');assert.equal(await p.locator('#csv').isEnabled(),true);checks.push('Invalid form cannot export stale result; confirmed reset recomputes');
async function download(id,name){const wait=p.waitForEvent('download');await p.click('#'+id);const file=path.join(out,name);await(await wait).saveAs(file);return fs.readFileSync(file);}
const json=JSON.parse((await download('json','experiment.json')).toString()),csv=(await download('csv','experiment.csv')).toString();assert.equal(json.schema,'queue-lab-v1');assert.equal(csv.split('\r\n').length,json.jobs.length*2+1);assert.deepEqual(json.pooled.records.map(j=>[j.arrival,j.service]),json.separate.records.map(j=>[j.arrival,j.service]));assert.match((await p.locator('.big').first().textContent()),new RegExp(json.pooled.metrics.meanWait.toFixed(1)));checks.push('Actual JSON and CSV downloads agree with rendered metrics and paired inputs');
const png=await download('png','chart.png');assert.equal(png.readUInt32BE(16),1100);assert.equal(png.readUInt32BE(20),460);assert.equal(png.toString('base64'),(await p.locator('#chart').evaluate(c=>c.toDataURL())).split(',')[1]);const reopened=await p.evaluate(async data=>{const i=new Image();i.src='data:image/png;base64,'+data;await i.decode();return [i.naturalWidth,i.naturalHeight];},png.toString('base64'));assert.deepEqual(reopened,[1100,460]);checks.push('Downloaded PNG reopened: 1100x460, exact preview bytes');
await p.locator('#servers').fill('1');await p.locator('#service').fill('300');await p.click('button[type=submit]');assert.match(await p.locator('#status').textContent(),/积压/);await p.click('#reset');await p.screenshot({path:path.join(out,'desktop.png'),fullPage:true});await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:path.join(out,'narrow.png'),fullPage:true});assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);assert.deepEqual(await p.evaluate(()=>[localStorage.length,sessionStorage.length]),[0,0]);checks.push('Overload warning, 390px layout, zero HTTP/storage/page errors');
fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({timestamp:new Date().toISOString(),browser:await b.version(),checks,status:'PASS',errors,requests,notRun:['Android/iOS devices','Safari/Firefox','Real store calibration','Cross-model review']},null,2));console.log(checks);await b.close();})().catch(e=>{console.error(e);process.exit(1)});
